package com.espiritware.opusclick.model;

public enum State {
	RETIRED("RETIRED"), 
	INACTIVE("INACTIVE"),
	WAITING_EMAIL_CONFIRMATION("WAITING_EMAIL_CONFIRMATION"),
	ACCOUNT_CONFIRMED("ACCOUNT_CONFIRMED"),
	WAITING_APPROVAL("WAITING_APPROVAL"),
	INCOMPLETED_PROFILE("INCOMPLETED_PROFILE"),
	READY("READY"),
	PENDING_BY_VISIT("PENDING_BY_VISIT"),
	PENDING_BY_QUOTATION("PENDING_BY_QUOTATION"),
	UNFULFILLED_VISIT_BY_USER("UNFULFILLED_VISIT_BY_USER"),
	UNFULFILLED_VISIT_BY_PROVIDER("UNFULFILLED_VISIT_BY_PROVIDER"),
	PENDING_BY_PROVIDER_ACCEPT("PENDING_BY_PROVIDER_ACCEPT"),
	PENDING_BY_USER_ACCEPT("PENDING_BY_USER_ACCEPT"),
	POSTPONE_BY_USER("POSTPONE_BY_USER"),
	POSTPONE_BY_PROVIDER("POSTPONE_BY_PROVIDER"),
	REJECTED_BY_USER("REJECTED_BY_USER"),
	REJECTED_BY_PROVIDER("REJECTED_BY_PROVIDER"),
	VISIT_MADE("VISIT_MADE"),
	ACCEPTED_BY_PROVIDER("ACCEPTED_BY_PROVIDER"),
	ACCEPTED_BY_USER("ACCEPTED_BY_USER");
	
	private String state;

	State(String state) {
        this.state = state;
    }

    public String state() {
        return state;
    }
}
