package com.espiritware.opusclick.model;

public enum State {
	/*User States*/
	RETIRED("RETIRED"), 
	INACTIVE("INACTIVE"),
	WAITING_EMAIL_CONFIRMATION("WAITING_EMAIL_CONFIRMATION"),
	ACCOUNT_CONFIRMED("ACCOUNT_CONFIRMED"),
	WAITING_APPROVAL("WAITING_APPROVAL"),
	INCOMPLETED_PROFILE("INCOMPLETED_PROFILE"),
	READY("READY"),
	/*Work States*/
	LABEL_CHANGE("LABEL_CHANGE"),
	PENDING_BY_VISIT("PENDING_BY_VISIT"),
	PENDING_BY_QUOTATION("PENDING_BY_QUOTATION"),
	QUOTE_MADE("QUOTE_MADE"),
	CONTRACT_MODIFIED_BY_USER("CONTRACT_MODIFIED_BY_USER"),
	CONTRACT_MODIFIED_BY_PROVIDER("CONTRACT_MODIFIED_BY_PROVIDER"),
	CONTRACT_ACCEPTED_BY_PROVIDER("CONTRACT_ACCEPTED_BY_PROVIDER"),
	CANCELLED_BY_USER("CANCELLED_BY_USER"),
	CANCELLED_BY_PROVIDER("CANCELLED_BY_PROVIDER"),
	PENDING_BY_PAYMENT("PENDING_BY_PAYMENT"),
	PARTIALLY_FINISHED("PARTIALLY_FINISHED"),
	/*Milestone States*/
	CREATED("CREATED"),
	IN_PROGRESS("IN_PROGRESS"),
	FINALIZED("FINALIZED"),
	PAID_OUT("PAID_OUT"),
	REPROBATE("REPROBATE"),
	UNFULFILLED("UNFULFILLED"),
	EXTENDED("EXTENDED"),
	DENIED("DENIED"),
	QUALIFIED("QUALIFIED"),
	UNFULFILLED_VISIT_BY_USER("UNFULFILLED_VISIT_BY_USER"),
	UNFULFILLED_VISIT_BY_PROVIDER("UNFULFILLED_VISIT_BY_PROVIDER"),
	/*Visit States*/
	PENDING_BY_PROVIDER_ACCEPT("PENDING_BY_PROVIDER_ACCEPT"),
	PENDING_BY_USER_ACCEPT("PENDING_BY_USER_ACCEPT"),
	POSTPONE_BY_USER("POSTPONE_BY_USER"),
	POSTPONE_BY_PROVIDER("POSTPONE_BY_PROVIDER"),
	REJECTED_BY_USER("REJECTED_BY_USER"),
	REJECTED_BY_PROVIDER("REJECTED_BY_PROVIDER"),
	VISIT_MADE("VISIT_MADE"),
	ACCEPTED_BY_PROVIDER("ACCEPTED_BY_PROVIDER"),
	ACCEPTED_BY_USER("ACCEPTED_BY_USER");
	

	
	private String state;

	State(String state) {
        this.state = state;
    }

    public String state() {
        return state;
    }
}
